name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      commit-hash:
        description: A full hash of the most recent commit from the 'develop' branch with green CI
        type: string
        required: true
      replay-tests-ok:
        description: All the DAILY_TEST_ON_PROD_DATA_* DAGs have no unknown failures 
        type: boolean
        required: true
      smoke-tests-ok:
        description: The CI_SMOKE_DEV_* DAGs (on testinfra) have no unknown failures list of DAGs to check and we have at least one successful run started after the last commit included in the PR hit develop branch.
        type: boolean
        required: true
      asana-tickets-ok:
        description: Asana tickets in P1 High pri - by EOD next business day section of buildcop project won't affect datacop's role in shipping out data to vendor and DREAM EOD today.
        type: boolean
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v4
      - name: Configure git identity
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          USER_LOGIN=$(gh api /repos/test-fh-org/deployment-test/actions/runs/7448529728/approvals --jq '.[].user.login')
          git config --global user.name "$USER_LOGIN"
      - name: deploy
        run: |
          echo "Deploying!"
          git tag release
          git push origin release
