name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      commit-hash:
        description: A full hash of the most recent commit from the 'develop' branch with green CI
        type: string
        required: true
      replay-tests-ok:
        description: All the DAILY_TEST_ON_PROD_DATA_* DAGs have no unknown failures 
        type: boolean
        required: true
      smoke-tests-ok:
        description: The CI_SMOKE_DEV_* DAGs (on testinfra) have no unknown failures list of DAGs to check and we have at least one successful run started after the last commit included in the PR hit develop branch.
        type: boolean
        required: true
      asana-tickets-ok:
        description: Asana tickets in P1 High pri - by EOD next business day section of buildcop project won't affect datacop's role in shipping out data to vendor and DREAM EOD today.
        type: boolean
        required: true

jobs:
  check-if-ci-green:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking if CI is green for a given commit..."
  smoke-dev-tests:
    runs-on: ubuntu-latest
    environment: Airflow smoke tests
    needs: [check-if-ci-green]
    steps:
      - run: echo "Starting and polling on smoke tests status..."
  replay-tests:
    runs-on: ubuntu-latest
    needs: [check-if-ci-green]
    steps:
      - run: echo "Starting and polling on replay tests status..."
  deployment-international:
    runs-on: ubuntu-latest
    environment: Prod
    needs: [smoke-dev-tests, replay-tests]
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: echo "Deploying!"
  deployment-us:
    runs-on: ubuntu-latest
    environment: Prod-US
    needs: [smoke-dev-tests, replay-tests]
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: echo "Deploying!"
