name: Prod deploymeny

on:
  workflow_dispatch:

jobs:

  smoke_DAG_tests:
    name: Smoke DAG tests
    runs-on: ubuntu-latest
    steps:
      - name: Logicless job
        run: >
          echo "This is a logicless job, meant to model a certain type of tests as a requirement
          for the prod deployment, and to be able to give explicit approval once the tests pass."
