name: Tests
on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        name:
          - foo
          - bar
    steps:
      - name: Hello world
        run: echo Hello ${{ matrix.name }}
